export const INCREMENT_SCORE = 'INCREMENT_SCORE';
export const DECREMENT_SCORE = 'DECREASE_SCORE';
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
